package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopRole;
import org.dgutstu.dgutshop.db.domain.DgutshopRoleExample;

public interface DgutshopRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    long countByExample(DgutshopRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int insert(DgutshopRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    DgutshopRole selectOneByExample(DgutshopRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    DgutshopRole selectOneByExampleSelective(@Param("example") DgutshopRoleExample example, @Param("selective") DgutshopRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    List<DgutshopRole> selectByExampleSelective(@Param("example") DgutshopRoleExample example, @Param("selective") DgutshopRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    List<DgutshopRole> selectByExample(DgutshopRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    DgutshopRole selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") DgutshopRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    DgutshopRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    DgutshopRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopRole record, @Param("example") DgutshopRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopRole record, @Param("example") DgutshopRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}