package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopCategoryItem;
import org.dgutstu.dgutshop.db.domain.DgutshopCategoryItemExample;

public interface DgutshopCategoryItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    long countByExample(DgutshopCategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopCategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int insert(DgutshopCategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopCategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    DgutshopCategoryItem selectOneByExample(DgutshopCategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    DgutshopCategoryItem selectOneByExampleSelective(@Param("example") DgutshopCategoryItemExample example, @Param("selective") DgutshopCategoryItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    List<DgutshopCategoryItem> selectByExampleSelective(@Param("example") DgutshopCategoryItemExample example, @Param("selective") DgutshopCategoryItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    List<DgutshopCategoryItem> selectByExample(DgutshopCategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    DgutshopCategoryItem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DgutshopCategoryItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    DgutshopCategoryItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    DgutshopCategoryItem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopCategoryItem record, @Param("example") DgutshopCategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopCategoryItem record, @Param("example") DgutshopCategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopCategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopCategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopCategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category_item
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}