package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopPermission;
import org.dgutstu.dgutshop.db.domain.DgutshopPermissionExample;

public interface DgutshopPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    long countByExample(DgutshopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int insert(DgutshopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    DgutshopPermission selectOneByExample(DgutshopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    DgutshopPermission selectOneByExampleSelective(@Param("example") DgutshopPermissionExample example, @Param("selective") DgutshopPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    List<DgutshopPermission> selectByExampleSelective(@Param("example") DgutshopPermissionExample example, @Param("selective") DgutshopPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    List<DgutshopPermission> selectByExample(DgutshopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    DgutshopPermission selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") DgutshopPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    DgutshopPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    DgutshopPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopPermission record, @Param("example") DgutshopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopPermission record, @Param("example") DgutshopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}