package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopProduct;
import org.dgutstu.dgutshop.db.domain.DgutshopProductExample;

public interface DgutshopProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    long countByExample(DgutshopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int insert(DgutshopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    DgutshopProduct selectOneByExample(DgutshopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    DgutshopProduct selectOneByExampleSelective(@Param("example") DgutshopProductExample example, @Param("selective") DgutshopProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    List<DgutshopProduct> selectByExampleSelective(@Param("example") DgutshopProductExample example, @Param("selective") DgutshopProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    List<DgutshopProduct> selectByExample(DgutshopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    DgutshopProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DgutshopProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    DgutshopProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    DgutshopProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopProduct record, @Param("example") DgutshopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopProduct record, @Param("example") DgutshopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}