package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopTopping;
import org.dgutstu.dgutshop.db.domain.DgutshopToppingExample;

public interface DgutshopToppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    long countByExample(DgutshopToppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopToppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int insert(DgutshopTopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopTopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    DgutshopTopping selectOneByExample(DgutshopToppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    DgutshopTopping selectOneByExampleSelective(@Param("example") DgutshopToppingExample example, @Param("selective") DgutshopTopping.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    List<DgutshopTopping> selectByExampleSelective(@Param("example") DgutshopToppingExample example, @Param("selective") DgutshopTopping.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    List<DgutshopTopping> selectByExample(DgutshopToppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    DgutshopTopping selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DgutshopTopping.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    DgutshopTopping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    DgutshopTopping selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopTopping record, @Param("example") DgutshopToppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopTopping record, @Param("example") DgutshopToppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopTopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopTopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopToppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_topping
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}