package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopLog;
import org.dgutstu.dgutshop.db.domain.DgutshopLogExample;

public interface DgutshopLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    long countByExample(DgutshopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int insert(DgutshopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    DgutshopLog selectOneByExample(DgutshopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    DgutshopLog selectOneByExampleSelective(@Param("example") DgutshopLogExample example, @Param("selective") DgutshopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    List<DgutshopLog> selectByExampleSelective(@Param("example") DgutshopLogExample example, @Param("selective") DgutshopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    List<DgutshopLog> selectByExample(DgutshopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    DgutshopLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DgutshopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    DgutshopLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    DgutshopLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopLog record, @Param("example") DgutshopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopLog record, @Param("example") DgutshopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}