package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopDelivery;
import org.dgutstu.dgutshop.db.domain.DgutshopDeliveryExample;

public interface DgutshopDeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    long countByExample(DgutshopDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int insert(DgutshopDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    DgutshopDelivery selectOneByExample(DgutshopDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    DgutshopDelivery selectOneByExampleSelective(@Param("example") DgutshopDeliveryExample example, @Param("selective") DgutshopDelivery.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    List<DgutshopDelivery> selectByExampleSelective(@Param("example") DgutshopDeliveryExample example, @Param("selective") DgutshopDelivery.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    List<DgutshopDelivery> selectByExample(DgutshopDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    DgutshopDelivery selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DgutshopDelivery.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    DgutshopDelivery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopDelivery record, @Param("example") DgutshopDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopDelivery record, @Param("example") DgutshopDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_delivery
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopDelivery record);
}