package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopOrderItem;
import org.dgutstu.dgutshop.db.domain.DgutshopOrderItemExample;

public interface DgutshopOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    long countByExample(DgutshopOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int insert(DgutshopOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    DgutshopOrderItem selectOneByExample(DgutshopOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    DgutshopOrderItem selectOneByExampleSelective(@Param("example") DgutshopOrderItemExample example, @Param("selective") DgutshopOrderItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    List<DgutshopOrderItem> selectByExampleSelective(@Param("example") DgutshopOrderItemExample example, @Param("selective") DgutshopOrderItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    List<DgutshopOrderItem> selectByExample(DgutshopOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    DgutshopOrderItem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DgutshopOrderItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    DgutshopOrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    DgutshopOrderItem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopOrderItem record, @Param("example") DgutshopOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopOrderItem record, @Param("example") DgutshopOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_order_item
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}