package org.dgutstu.dgutshop.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dgutstu.dgutshop.db.domain.DgutshopCategory;
import org.dgutstu.dgutshop.db.domain.DgutshopCategoryExample;

public interface DgutshopCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    long countByExample(DgutshopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int deleteByExample(DgutshopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int insert(DgutshopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int insertSelective(DgutshopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    DgutshopCategory selectOneByExample(DgutshopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    DgutshopCategory selectOneByExampleSelective(@Param("example") DgutshopCategoryExample example, @Param("selective") DgutshopCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    List<DgutshopCategory> selectByExampleSelective(@Param("example") DgutshopCategoryExample example, @Param("selective") DgutshopCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    List<DgutshopCategory> selectByExample(DgutshopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    DgutshopCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DgutshopCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    DgutshopCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    DgutshopCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DgutshopCategory record, @Param("example") DgutshopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DgutshopCategory record, @Param("example") DgutshopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DgutshopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DgutshopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DgutshopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dgutshop_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}